language: c
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev libapr1-dev libaprutil1-dev apache2 libcap-dev curl
env:
  - HTTPD_VERSION=httpd-2.4.43
    HTTPD_CONFIG_OPT="--with-mpm=prefork"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1 
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz 
    APR_TAR=${APR}.tar.gz 
    APR_UTIL_TAR=${APR_UTIL}.tar.gz 
    APXS_CHECK_CMD="../${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="test/mod_process_security.conf.2.4"
    VHOST_DAV_CONF="test/mod_process_security.dav.conf.2.4"
    DEFAULT_DIR="/home/travis/build/matsumotory/mod_process_security/"
  #- HTTPD_VERSION=httpd-2.4.17 
before_script:
  - cd ../
  - wget http://ftp.jaist.ac.jp/pub/apache//httpd/${HTTPD_TAR}
  - tar xf ${HTTPD_TAR}
  - cd ${HTTPD_VERSION}/srclib
  - wget http://ftp.jaist.ac.jp/pub/apache//apr/${APR_TAR}
  - wget http://ftp.jaist.ac.jp/pub/apache//apr/${APR_UTIL_TAR}
  - tar xf ${APR_TAR}
  - tar xf ${APR_UTIL_TAR}
  - ln -s ${APR} apr
  - ln -s ${APR_UTIL} apr-util
  - cd ..
  - ./configure --prefix=`pwd`/apache --with-included-apr ${HTTPD_CONFIG_OPT}
  - make
  - make install
  - cd ../mod_process_security
  - echo ${APXS_CHECK_CMD}
  - ${APXS_CHECK_CMD}

  # setup test : TODO: use scripts
  - sudo chown 500.500 test/id.cgi
  - sudo chmod 755 test/id.cgi
  - sudo cp -p test/id.cgi $(../${HTTPD_VERSION}/apache/bin/apxs -q exp_cgidir)/.

  - sudo chown 600.700 test/id2.cgi
  - sudo chmod 700 test/id2.cgi
  - sudo cp -p test/id2.cgi $(../${HTTPD_VERSION}/apache/bin/apxs -q exp_cgidir)/.

  # backup default server config
  - sudo cp $(../${HTTPD_VERSION}/apache/bin/apxs -q sysconfdir)/$(../${HTTPD_VERSION}/apache/bin/apxs -q progname).conf /tmp/

  # setup server config
  - sudo sed -i "s/^Listen/#Listen/" $(../${HTTPD_VERSION}/apache/bin/apxs -q sysconfdir)/$(../${HTTPD_VERSION}/apache/bin/apxs -q progname).conf
  - sudo cat ${VHOST_CONF} >> $(../${HTTPD_VERSION}/apache/bin/apxs -q sysconfdir)/$(../${HTTPD_VERSION}/apache/bin/apxs -q progname).conf
  - sudo make APXS=../${HTTPD_VERSION}/apache/bin/apxs APACHECTL=../${HTTPD_VERSION}/apache/bin/apachectl install
  - sudo make APXS=../${HTTPD_VERSION}/apache/bin/apxs APACHECTL=../${HTTPD_VERSION}/apache/bin/apachectl restart
script:
  # debug
  - pwd
  - sudo ls -la $(../${HTTPD_VERSION}/apache/bin/apxs -q exp_cgidir)/
  - sudo netstat -lnpt
  - sudo cat $(../${HTTPD_VERSION}/apache/bin/apxs -q sysconfdir)/$(../${HTTPD_VERSION}/apache/bin/apxs -q progname).conf

  # test
  - make APXS=../${HTTPD_VERSION}/apache/bin/apxs test

  # debug
  - sudo cat $(../${HTTPD_VERSION}/apache/bin/apxs -q exp_logfiledir)/error_log

  # build mruby
  - cd test && git clone --depth=1 git://github.com/mruby/mruby.git
  - cd mruby && MRUBY_CONFIG=../build_config.rb rake

  #--------------------#
  # General Test Suite #
  #--------------------#

  # run test.rb
  - sudo chown 755 /home/travis/build
  - cd ${DEFAULT_DIR}/test 
  - ./mruby/bin/mruby ./test.rb
  - cd ${DEFAULT_DIR}
  - sudo cat $(../${HTTPD_VERSION}/apache/bin/apxs -q exp_logfiledir)/error_log

